var grinderStructure = makeAllStructureVariants ([
    //hoppers layer
{x: -1, y: +1, z:  0, id: 154},
{x:  0, y: +1, z:  0, id: 154},
{x: +1, y: +1, z:  0, id: 154},
{x: -1, y: +1, z: +1, id: 154},
{x:  0, y: +1, z: +1, id: 154},
{x: +1, y: +1, z: +1, id: 154},
{x: -1, y: +1, z: +2, id: 154},
{x:  0, y: +1, z: +2, id: 154},
{x: +1, y: +1, z: +2, id: 154},
    //energy layer x3
{x: -1, y: 0, z:  0, id: BlockID.machineScaffolding},
{x:  0, y: 0, z:  0, id: BlockID.machineBlockLight},
{x: +1, y: 0, z:  0, id: BlockID.machineScaffolding},
{x: -1, y: 0, z: +1, id: BlockID.machineBlockLight},
{x:  0, y: 0, z: +1, id: BlockID.machineBlockHeavy},
{x: +1, y: 0, z: +1, id: BlockID.machineBlockLight},
{x: -1, y: 0, z: +2, id: BlockID.machineScaffolding},
{x:  0, y: 0, z: +2, id: BlockID.machineBlockLight},
{x: +1, y: 0, z: +2, id: BlockID.machineScaffolding},
    
{x: -1, y: 0, z:  0, id: BlockID.machineScaffolding},
{x:  0, y: 0, z:  0, id: BlockID.machineBlockLight},
{x: +1, y: 0, z:  0, id: BlockID.machineScaffolding},
{x: -1, y: 0, z: +1, id: BlockID.machineBlockLight},
{x:  0, y: 0, z: +1, id: BlockID.machineBlockHeavy},
{x: +1, y: 0, z: +1, id: BlockID.machineBlockLight},
{x: -1, y: 0, z: +2, id: BlockID.machineScaffolding},
{x:  0, y: 0, z: +2, id: BlockID.machineBlockLight},
{x: +1, y: 0, z: +2, id: BlockID.machineScaffolding},
    
{x: -1, y: 0, z:  0, id: BlockID.machineScaffolding},
{x:  0, y: 0, z:  0, id: BlockID.machineBlockLight},
{x: +1, y: 0, z:  0, id: BlockID.machineScaffolding},
{x: -1, y: 0, z: +1, id: BlockID.machineBlockLight},
{x:  0, y: 0, z: +1, id: BlockID.machineBlockHeavy},
{x: +1, y: 0, z: +1, id: BlockID.machineBlockLight},
{x: -1, y: 0, z: +2, id: BlockID.machineScaffolding},
{x:  0, y: 0, z: +2, id: BlockID.machineBlockLight},
{x: +1, y: 0, z: +2, id: BlockID.machineScaffolding},
    //bottom layer
{x: -1, y: 0, z:  0, id: BlockID.machineBlockLight},
{x:  0, y: 0, z:  0, id: BlockID.sheetmetalSteel},
{x: +1, y: 0, z:  0, id: BlockID.machineBlockLight},
{x: -1, y: 0, z: +1, id: BlockID.sheetmetalSteel},
{x:  0, y: 0, z: +1, id: BlockID.sheetmetalSteel},
{x: +1, y: 0, z: +1, id: BlockID.sheetmetalSteel},
{x: -1, y: 0, z: +2, id: BlockID.machineBlockLight},
{x:  0, y: 0, z: +2, id: BlockID.sheetmetalSteel},
{x: +1, y: 0, z: +2, id: BlockID.machineBlockLight},
]);