var crusherStructure = makeAllStructureVariants ([
    
{x:  0, y:  0, z:  0, id: BlockID.crusherCore},
{x: +1, y:  0, z:  0, id: BlockID.machineBlockLight},
{x:  0, y: -1, z:  0, id: BlockID.machineScaffolding},
{x: +1, y: -1, z:  0, id: BlockID.machineScaffolding},
{x: +2, y: -1, z:  0, id: BlockID.machineScaffolding},

{x:  0, y: +1, z: +1, id: 154},
{x: +1, y: +1, z: +1, id: 154},
{x: +2, y: +1, z: +1, id: 154},
{x:  0, y:  0, z: +1, id: BlockID.fenceSteel},   
{x: +1, y:  0, z: +1, id: BlockID.fenceSteel},
{x: +2, y:  0, z: +1, id: BlockID.fenceSteel},
{x:  0, y: -1, z: +1, id: BlockID.machineScaffolding},
{x: +1, y: -1, z: +1, id: BlockID.machineScaffolding},
{x: +2, y: -1, z: +1, id: BlockID.machineScaffolding},

{x:  0, y: +1, z: +2, id: 154},
{x: +1, y: +1, z: +2, id: 154},
{x: +2, y: +1, z: +2, id: 154},
{x:  0, y:  0, z: +2, id: BlockID.fenceSteel},
{x: +1, y:  0, z: +2, id: BlockID.machineBlockLight},
{x: +2, y:  0, z: +2, id: BlockID.fenceSteel},
{x:  0, y: -1, z: +2, id: BlockID.machineBlockLight},
{x: +1, y: -1, z: +2, id: BlockID.machineBlockLight},
{x: +2, y: -1, z: +2, id: BlockID.machineScaffolding},

{x:  0, y: +1, z: +3, id: 154},
{x: +1, y: +1, z: +3, id: 154},
{x: +2, y: +1, z: +3, id: 154},
{x:  0, y:  0, z: +3, id: BlockID.fenceSteel},
{x: +1, y:  0, z: +3, id: BlockID.fenceSteel},
{x: +2, y:  0, z: +3, id: BlockID.fenceSteel},
{x:  0, y: -1, z: +3, id: BlockID.machineScaffolding},
{x: +1, y: -1, z: +3, id: BlockID.machineScaffolding},
{x: +2, y: -1, z: +3, id: BlockID.machineScaffolding},

{x:  0, y:  0, z: +4, id: BlockID.machineBlockLight},
{x: +1, y:  0, z: +4, id: BlockID.machineBlockLight},
{x: +2, y:  0, z: +4, id: BlockID.machineBlockLight},
{x:  0, y: -1, z: +4, id: BlockID.machineBlockLight},
{x: +1, y: -1, z: +4, id: BlockID.machineBlockLight},
{x: +2, y: -1, z: +4, id: BlockID.machineBlockLight}
]);